
lag_lists = [[{'trial': 0, 'lag': 23, 'event': 'study'}, {'trial': 0, 'lag': 10, 'event': 'study'}, {'trial': 1, 'lag': 23, 'event': 'study'}, {'trial': 0, 'lag': 0, 'event': 'study'}, {'trial': 0, 'lag': 0, 'event': 'test1'}, {'trial': 0, 'lag': 0, 'event': 'test2'}, {'trial': 0, 'lag': 1, 'event': 'study'}, {'trial': 0, 'lag': 2, 'event': 'study'}, {'trial': 0, 'lag': 1, 'event': 'test1'}, {'trial': 0, 'lag': 1, 'event': 'test2'}, {'trial': 0, 'lag': 2, 'event': 'test1'}, {'trial': 0, 'lag': 2, 'event': 'test2'}, {'trial': 0, 'lag': 10, 'event': 'test1'}, {'trial': 0, 'lag': 10, 'event': 'test2'}, {'trial': 0, 'lag': 24, 'event': 'study'}, {'trial': 1, 'lag': 25, 'event': 'study'}, {'trial': 1, 'lag': 12, 'event': 'study'}, {'trial': 1, 'lag': 1, 'event': 'study'}, {'trial': 1, 'lag': 24, 'event': 'study'}, {'trial': 1, 'lag': 1, 'event': 'test1'}, {'trial': 1, 'lag': 1, 'event': 'test2'}, {'trial': 0, 'lag': 25, 'event': 'study'}, {'trial': 1, 'lag': 11, 'event': 'study'}, {'trial': 0, 'lag': 12, 'event': 'study'}, {'trial': 0, 'lag': 23, 'event': 'test1'}, {'trial': 0, 'lag': 23, 'event': 'test2'}, {'trial': 1, 'lag': 23, 'event': 'test1'}, {'trial': 1, 'lag': 23, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'study'}, {'trial': 1, 'lag': 12, 'event': 'test1'}, {'trial': 1, 'lag': 12, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'test1'}, {'trial': 1, 'lag': 2, 'event': 'test2'}, {'trial': 0, 'lag': 11, 'event': 'study'}, {'trial': 1, 'lag': 11, 'event': 'test1'}, {'trial': 1, 'lag': 11, 'event': 'test2'}, {'trial': 0, 'lag': 12, 'event': 'test1'}, {'trial': 0, 'lag': 12, 'event': 'test2'}, {'trial': 1, 'lag': 10, 'event': 'study'}, {'trial': 0, 'lag': 24, 'event': 'test1'}, {'trial': 0, 'lag': 24, 'event': 'test2'}, {'trial': 1, 'lag': 25, 'event': 'test1'}, {'trial': 1, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 24, 'event': 'test1'}, {'trial': 1, 'lag': 24, 'event': 'test2'}, {'trial': 0, 'lag': 11, 'event': 'test1'}, {'trial': 0, 'lag': 11, 'event': 'test2'}, {'trial': 0, 'lag': 25, 'event': 'test1'}, {'trial': 0, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 10, 'event': 'test1'}, {'trial': 1, 'lag': 10, 'event': 'test2'}, {'trial': 1, 'lag': 0, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'test1'}, {'trial': 1, 'lag': 0, 'event': 'test2'}],
#
[{'trial': 0, 'lag': 10, 'event': 'study'}, {'trial': 0, 'lag': 2, 'event': 'study'}, {'trial': 0, 'lag': 25, 'event': 'study'}, {'trial': 1, 'lag': 12, 'event': 'study'}, {'trial': 0, 'lag': 2, 'event': 'test1'}, {'trial': 0, 'lag': 2, 'event': 'test2'}, {'trial': 1, 'lag': 1, 'event': 'study'}, {'trial': 1, 'lag': 24, 'event': 'study'}, {'trial': 1, 'lag': 1, 'event': 'test1'}, {'trial': 1, 'lag': 1, 'event': 'test2'}, {'trial': 1, 'lag': 10, 'event': 'study'}, {'trial': 0, 'lag': 10, 'event': 'test1'}, {'trial': 0, 'lag': 10, 'event': 'test2'}, {'trial': 0, 'lag': 12, 'event': 'study'}, {'trial': 1, 'lag': 23, 'event': 'study'}, {'trial': 0, 'lag': 24, 'event': 'study'}, {'trial': 1, 'lag': 12, 'event': 'test1'}, {'trial': 1, 'lag': 12, 'event': 'test2'}, {'trial': 0, 'lag': 11, 'event': 'study'}, {'trial': 1, 'lag': 25, 'event': 'study'}, {'trial': 1, 'lag': 2, 'event': 'study'}, {'trial': 1, 'lag': 10, 'event': 'test1'}, {'trial': 1, 'lag': 10, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'test1'}, {'trial': 1, 'lag': 2, 'event': 'test2'}, {'trial': 0, 'lag': 23, 'event': 'study'}, {'trial': 0, 'lag': 12, 'event': 'test1'}, {'trial': 0, 'lag': 12, 'event': 'test2'}, {'trial': 0, 'lag': 25, 'event': 'test1'}, {'trial': 0, 'lag': 25, 'event': 'test2'}, {'trial': 0, 'lag': 11, 'event': 'test1'}, {'trial': 0, 'lag': 11, 'event': 'test2'}, {'trial': 1, 'lag': 24, 'event': 'test1'}, {'trial': 1, 'lag': 24, 'event': 'test2'}, {'trial': 0, 'lag': 1, 'event': 'study'}, {'trial': 1, 'lag': 11, 'event': 'study'}, {'trial': 0, 'lag': 1, 'event': 'test1'}, {'trial': 0, 'lag': 1, 'event': 'test2'}, {'trial': 1, 'lag': 23, 'event': 'test1'}, {'trial': 1, 'lag': 23, 'event': 'test2'}, {'trial': 0, 'lag': 24, 'event': 'test1'}, {'trial': 0, 'lag': 24, 'event': 'test2'}, {'trial': 1, 'lag': 0, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'test1'}, {'trial': 1, 'lag': 0, 'event': 'test2'}, {'trial': 1, 'lag': 25, 'event': 'test1'}, {'trial': 1, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 11, 'event': 'test1'}, {'trial': 1, 'lag': 11, 'event': 'test2'}, {'trial': 0, 'lag': 23, 'event': 'test1'}, {'trial': 0, 'lag': 23, 'event': 'test2'}, {'trial': 0, 'lag': 0, 'event': 'study'}, {'trial': 0, 'lag': 0, 'event': 'test1'}, {'trial': 0, 'lag': 0, 'event': 'test2'}],
#
[{'trial': 0, 'lag': 0, 'event': 'study'}, {'trial': 0, 'lag': 0, 'event': 'test1'}, {'trial': 0, 'lag': 0, 'event': 'test2'}, {'trial': 0, 'lag': 23, 'event': 'study'}, {'trial': 1, 'lag': 10, 'event': 'study'}, {'trial': 0, 'lag': 24, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'test1'}, {'trial': 1, 'lag': 0, 'event': 'test2'}, {'trial': 1, 'lag': 23, 'event': 'study'}, {'trial': 0, 'lag': 12, 'event': 'study'}, {'trial': 1, 'lag': 24, 'event': 'study'}, {'trial': 0, 'lag': 25, 'event': 'study'}, {'trial': 0, 'lag': 11, 'event': 'study'}, {'trial': 1, 'lag': 25, 'event': 'study'}, {'trial': 1, 'lag': 10, 'event': 'test1'}, {'trial': 1, 'lag': 10, 'event': 'test2'}, {'trial': 0, 'lag': 1, 'event': 'study'}, {'trial': 0, 'lag': 2, 'event': 'study'}, {'trial': 0, 'lag': 1, 'event': 'test1'}, {'trial': 0, 'lag': 1, 'event': 'test2'}, {'trial': 0, 'lag': 2, 'event': 'test1'}, {'trial': 0, 'lag': 2, 'event': 'test2'}, {'trial': 0, 'lag': 12, 'event': 'test1'}, {'trial': 0, 'lag': 12, 'event': 'test2'}, {'trial': 0, 'lag': 11, 'event': 'test1'}, {'trial': 0, 'lag': 11, 'event': 'test2'}, {'trial': 0, 'lag': 23, 'event': 'test1'}, {'trial': 0, 'lag': 23, 'event': 'test2'}, {'trial': 1, 'lag': 12, 'event': 'study'}, {'trial': 0, 'lag': 24, 'event': 'test1'}, {'trial': 0, 'lag': 24, 'event': 'test2'}, {'trial': 1, 'lag': 11, 'event': 'study'}, {'trial': 1, 'lag': 23, 'event': 'test1'}, {'trial': 1, 'lag': 23, 'event': 'test2'}, {'trial': 0, 'lag': 10, 'event': 'study'}, {'trial': 1, 'lag': 24, 'event': 'test1'}, {'trial': 1, 'lag': 24, 'event': 'test2'}, {'trial': 0, 'lag': 25, 'event': 'test1'}, {'trial': 0, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 25, 'event': 'test1'}, {'trial': 1, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 12, 'event': 'test1'}, {'trial': 1, 'lag': 12, 'event': 'test2'}, {'trial': 1, 'lag': 11, 'event': 'test1'}, {'trial': 1, 'lag': 11, 'event': 'test2'}, {'trial': 0, 'lag': 10, 'event': 'test1'}, {'trial': 0, 'lag': 10, 'event': 'test2'}, {'trial': 1, 'lag': 1, 'event': 'study'}, {'trial': 1, 'lag': 2, 'event': 'study'}, {'trial': 1, 'lag': 1, 'event': 'test1'}, {'trial': 1, 'lag': 1, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'test1'}, {'trial': 1, 'lag': 2, 'event': 'test2'}],
#
[{'trial': 1, 'lag': 25, 'event': 'study'}, {'trial': 1, 'lag': 11, 'event': 'study'}, {'trial': 0, 'lag': 12, 'event': 'study'}, {'trial': 0, 'lag': 1, 'event': 'study'}, {'trial': 1, 'lag': 23, 'event': 'study'}, {'trial': 0, 'lag': 1, 'event': 'test1'}, {'trial': 0, 'lag': 1, 'event': 'test2'}, {'trial': 1, 'lag': 24, 'event': 'study'}, {'trial': 1, 'lag': 10, 'event': 'study'}, {'trial': 1, 'lag': 1, 'event': 'study'}, {'trial': 0, 'lag': 23, 'event': 'study'}, {'trial': 1, 'lag': 1, 'event': 'test1'}, {'trial': 1, 'lag': 1, 'event': 'test2'}, {'trial': 1, 'lag': 11, 'event': 'test1'}, {'trial': 1, 'lag': 11, 'event': 'test2'}, {'trial': 0, 'lag': 12, 'event': 'test1'}, {'trial': 0, 'lag': 12, 'event': 'test2'}, {'trial': 0, 'lag': 24, 'event': 'study'}, {'trial': 0, 'lag': 11, 'event': 'study'}, {'trial': 1, 'lag': 10, 'event': 'test1'}, {'trial': 1, 'lag': 10, 'event': 'test2'}, {'trial': 0, 'lag': 2, 'event': 'study'}, {'trial': 0, 'lag': 25, 'event': 'study'}, {'trial': 1, 'lag': 12, 'event': 'study'}, {'trial': 0, 'lag': 2, 'event': 'test1'}, {'trial': 0, 'lag': 2, 'event': 'test2'}, {'trial': 1, 'lag': 25, 'event': 'test1'}, {'trial': 1, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 23, 'event': 'test1'}, {'trial': 1, 'lag': 23, 'event': 'test2'}, {'trial': 0, 'lag': 11, 'event': 'test1'}, {'trial': 0, 'lag': 11, 'event': 'test2'}, {'trial': 1, 'lag': 24, 'event': 'test1'}, {'trial': 1, 'lag': 24, 'event': 'test2'}, {'trial': 0, 'lag': 23, 'event': 'test1'}, {'trial': 0, 'lag': 23, 'event': 'test2'}, {'trial': 1, 'lag': 12, 'event': 'test1'}, {'trial': 1, 'lag': 12, 'event': 'test2'}, {'trial': 0, 'lag': 0, 'event': 'study'}, {'trial': 0, 'lag': 0, 'event': 'test1'}, {'trial': 0, 'lag': 0, 'event': 'test2'}, {'trial': 0, 'lag': 10, 'event': 'study'}, {'trial': 0, 'lag': 24, 'event': 'test1'}, {'trial': 0, 'lag': 24, 'event': 'test2'}, {'trial': 1, 'lag': 0, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'test1'}, {'trial': 1, 'lag': 0, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'study'}, {'trial': 0, 'lag': 25, 'event': 'test1'}, {'trial': 0, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'test1'}, {'trial': 1, 'lag': 2, 'event': 'test2'}, {'trial': 0, 'lag': 10, 'event': 'test1'}, {'trial': 0, 'lag': 10, 'event': 'test2'}],
#
[{'trial': 1, 'lag': 24, 'event': 'study'}, {'trial': 0, 'lag': 11, 'event': 'study'}, {'trial': 0, 'lag': 25, 'event': 'study'}, {'trial': 0, 'lag': 12, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'test1'}, {'trial': 1, 'lag': 0, 'event': 'test2'}, {'trial': 1, 'lag': 23, 'event': 'study'}, {'trial': 0, 'lag': 0, 'event': 'study'}, {'trial': 0, 'lag': 0, 'event': 'test1'}, {'trial': 0, 'lag': 0, 'event': 'test2'}, {'trial': 0, 'lag': 24, 'event': 'study'}, {'trial': 1, 'lag': 25, 'event': 'study'}, {'trial': 0, 'lag': 11, 'event': 'test1'}, {'trial': 0, 'lag': 11, 'event': 'test2'}, {'trial': 0, 'lag': 2, 'event': 'study'}, {'trial': 0, 'lag': 12, 'event': 'test1'}, {'trial': 0, 'lag': 12, 'event': 'test2'}, {'trial': 0, 'lag': 2, 'event': 'test1'}, {'trial': 0, 'lag': 2, 'event': 'test2'}, {'trial': 0, 'lag': 23, 'event': 'study'}, {'trial': 0, 'lag': 1, 'event': 'study'}, {'trial': 0, 'lag': 10, 'event': 'study'}, {'trial': 0, 'lag': 1, 'event': 'test1'}, {'trial': 0, 'lag': 1, 'event': 'test2'}, {'trial': 1, 'lag': 24, 'event': 'test1'}, {'trial': 1, 'lag': 24, 'event': 'test2'}, {'trial': 1, 'lag': 12, 'event': 'study'}, {'trial': 0, 'lag': 25, 'event': 'test1'}, {'trial': 0, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 11, 'event': 'study'}, {'trial': 1, 'lag': 23, 'event': 'test1'}, {'trial': 1, 'lag': 23, 'event': 'test2'}, {'trial': 0, 'lag': 10, 'event': 'test1'}, {'trial': 0, 'lag': 10, 'event': 'test2'}, {'trial': 1, 'lag': 10, 'event': 'study'}, {'trial': 0, 'lag': 24, 'event': 'test1'}, {'trial': 0, 'lag': 24, 'event': 'test2'}, {'trial': 1, 'lag': 25, 'event': 'test1'}, {'trial': 1, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 12, 'event': 'test1'}, {'trial': 1, 'lag': 12, 'event': 'test2'}, {'trial': 1, 'lag': 11, 'event': 'test1'}, {'trial': 1, 'lag': 11, 'event': 'test2'}, {'trial': 0, 'lag': 23, 'event': 'test1'}, {'trial': 0, 'lag': 23, 'event': 'test2'}, {'trial': 1, 'lag': 10, 'event': 'test1'}, {'trial': 1, 'lag': 10, 'event': 'test2'}, {'trial': 1, 'lag': 1, 'event': 'study'}, {'trial': 1, 'lag': 2, 'event': 'study'}, {'trial': 1, 'lag': 1, 'event': 'test1'}, {'trial': 1, 'lag': 1, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'test1'}, {'trial': 1, 'lag': 2, 'event': 'test2'}],
#
[{'trial': 0, 'lag': 23, 'event': 'study'}, {'trial': 0, 'lag': 25, 'event': 'study'}, {'trial': 1, 'lag': 10, 'event': 'study'}, {'trial': 1, 'lag': 1, 'event': 'study'}, {'trial': 0, 'lag': 11, 'event': 'study'}, {'trial': 1, 'lag': 1, 'event': 'test1'}, {'trial': 1, 'lag': 1, 'event': 'test2'}, {'trial': 1, 'lag': 11, 'event': 'study'}, {'trial': 0, 'lag': 2, 'event': 'study'}, {'trial': 1, 'lag': 12, 'event': 'study'}, {'trial': 0, 'lag': 24, 'event': 'study'}, {'trial': 0, 'lag': 2, 'event': 'test1'}, {'trial': 0, 'lag': 2, 'event': 'test2'}, {'trial': 1, 'lag': 10, 'event': 'test1'}, {'trial': 1, 'lag': 10, 'event': 'test2'}, {'trial': 1, 'lag': 25, 'event': 'study'}, {'trial': 0, 'lag': 11, 'event': 'test1'}, {'trial': 0, 'lag': 11, 'event': 'test2'}, {'trial': 1, 'lag': 24, 'event': 'study'}, {'trial': 1, 'lag': 11, 'event': 'test1'}, {'trial': 1, 'lag': 11, 'event': 'test2'}, {'trial': 1, 'lag': 23, 'event': 'study'}, {'trial': 1, 'lag': 12, 'event': 'test1'}, {'trial': 1, 'lag': 12, 'event': 'test2'}, {'trial': 0, 'lag': 23, 'event': 'test1'}, {'trial': 0, 'lag': 23, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'study'}, {'trial': 0, 'lag': 25, 'event': 'test1'}, {'trial': 0, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'test1'}, {'trial': 1, 'lag': 2, 'event': 'test2'}, {'trial': 1, 'lag': 0, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'test1'}, {'trial': 1, 'lag': 0, 'event': 'test2'}, {'trial': 0, 'lag': 12, 'event': 'study'}, {'trial': 0, 'lag': 24, 'event': 'test1'}, {'trial': 0, 'lag': 24, 'event': 'test2'}, {'trial': 0, 'lag': 1, 'event': 'study'}, {'trial': 0, 'lag': 10, 'event': 'study'}, {'trial': 0, 'lag': 1, 'event': 'test1'}, {'trial': 0, 'lag': 1, 'event': 'test2'}, {'trial': 1, 'lag': 25, 'event': 'test1'}, {'trial': 1, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 24, 'event': 'test1'}, {'trial': 1, 'lag': 24, 'event': 'test2'}, {'trial': 1, 'lag': 23, 'event': 'test1'}, {'trial': 1, 'lag': 23, 'event': 'test2'}, {'trial': 0, 'lag': 12, 'event': 'test1'}, {'trial': 0, 'lag': 12, 'event': 'test2'}, {'trial': 0, 'lag': 10, 'event': 'test1'}, {'trial': 0, 'lag': 10, 'event': 'test2'}, {'trial': 0, 'lag': 0, 'event': 'study'}, {'trial': 0, 'lag': 0, 'event': 'test1'}, {'trial': 0, 'lag': 0, 'event': 'test2'}],
#
[{'trial': 0, 'lag': 24, 'event': 'study'}, {'trial': 0, 'lag': 10, 'event': 'study'}, {'trial': 0, 'lag': 0, 'event': 'study'}, {'trial': 0, 'lag': 0, 'event': 'test1'}, {'trial': 0, 'lag': 0, 'event': 'test2'}, {'trial': 1, 'lag': 25, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'test1'}, {'trial': 1, 'lag': 0, 'event': 'test2'}, {'trial': 1, 'lag': 24, 'event': 'study'}, {'trial': 0, 'lag': 25, 'event': 'study'}, {'trial': 0, 'lag': 11, 'event': 'study'}, {'trial': 0, 'lag': 10, 'event': 'test1'}, {'trial': 0, 'lag': 10, 'event': 'test2'}, {'trial': 0, 'lag': 23, 'event': 'study'}, {'trial': 1, 'lag': 12, 'event': 'study'}, {'trial': 1, 'lag': 1, 'event': 'study'}, {'trial': 1, 'lag': 2, 'event': 'study'}, {'trial': 1, 'lag': 1, 'event': 'test1'}, {'trial': 1, 'lag': 1, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'test1'}, {'trial': 1, 'lag': 2, 'event': 'test2'}, {'trial': 1, 'lag': 23, 'event': 'study'}, {'trial': 0, 'lag': 11, 'event': 'test1'}, {'trial': 0, 'lag': 11, 'event': 'test2'}, {'trial': 0, 'lag': 24, 'event': 'test1'}, {'trial': 0, 'lag': 24, 'event': 'test2'}, {'trial': 0, 'lag': 12, 'event': 'study'}, {'trial': 1, 'lag': 12, 'event': 'test1'}, {'trial': 1, 'lag': 12, 'event': 'test2'}, {'trial': 1, 'lag': 11, 'event': 'study'}, {'trial': 1, 'lag': 25, 'event': 'test1'}, {'trial': 1, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 10, 'event': 'study'}, {'trial': 1, 'lag': 24, 'event': 'test1'}, {'trial': 1, 'lag': 24, 'event': 'test2'}, {'trial': 0, 'lag': 25, 'event': 'test1'}, {'trial': 0, 'lag': 25, 'event': 'test2'}, {'trial': 0, 'lag': 23, 'event': 'test1'}, {'trial': 0, 'lag': 23, 'event': 'test2'}, {'trial': 0, 'lag': 12, 'event': 'test1'}, {'trial': 0, 'lag': 12, 'event': 'test2'}, {'trial': 1, 'lag': 11, 'event': 'test1'}, {'trial': 1, 'lag': 11, 'event': 'test2'}, {'trial': 1, 'lag': 10, 'event': 'test1'}, {'trial': 1, 'lag': 10, 'event': 'test2'}, {'trial': 1, 'lag': 23, 'event': 'test1'}, {'trial': 1, 'lag': 23, 'event': 'test2'}, {'trial': 0, 'lag': 1, 'event': 'study'}, {'trial': 0, 'lag': 2, 'event': 'study'}, {'trial': 0, 'lag': 1, 'event': 'test1'}, {'trial': 0, 'lag': 1, 'event': 'test2'}, {'trial': 0, 'lag': 2, 'event': 'test1'}, {'trial': 0, 'lag': 2, 'event': 'test2'}],
#
[{'trial': 1, 'lag': 1, 'event': 'study'}, {'trial': 1, 'lag': 23, 'event': 'study'}, {'trial': 1, 'lag': 1, 'event': 'test1'}, {'trial': 1, 'lag': 1, 'event': 'test2'}, {'trial': 0, 'lag': 1, 'event': 'study'}, {'trial': 0, 'lag': 23, 'event': 'study'}, {'trial': 0, 'lag': 1, 'event': 'test1'}, {'trial': 0, 'lag': 1, 'event': 'test2'}, {'trial': 1, 'lag': 24, 'event': 'study'}, {'trial': 0, 'lag': 10, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'test1'}, {'trial': 1, 'lag': 0, 'event': 'test2'}, {'trial': 1, 'lag': 25, 'event': 'study'}, {'trial': 1, 'lag': 12, 'event': 'study'}, {'trial': 0, 'lag': 0, 'event': 'study'}, {'trial': 0, 'lag': 0, 'event': 'test1'}, {'trial': 0, 'lag': 0, 'event': 'test2'}, {'trial': 0, 'lag': 24, 'event': 'study'}, {'trial': 0, 'lag': 11, 'event': 'study'}, {'trial': 0, 'lag': 10, 'event': 'test1'}, {'trial': 0, 'lag': 10, 'event': 'test2'}, {'trial': 0, 'lag': 25, 'event': 'study'}, {'trial': 1, 'lag': 11, 'event': 'study'}, {'trial': 0, 'lag': 12, 'event': 'study'}, {'trial': 1, 'lag': 23, 'event': 'test1'}, {'trial': 1, 'lag': 23, 'event': 'test2'}, {'trial': 1, 'lag': 12, 'event': 'test1'}, {'trial': 1, 'lag': 12, 'event': 'test2'}, {'trial': 0, 'lag': 23, 'event': 'test1'}, {'trial': 0, 'lag': 23, 'event': 'test2'}, {'trial': 0, 'lag': 11, 'event': 'test1'}, {'trial': 0, 'lag': 11, 'event': 'test2'}, {'trial': 1, 'lag': 24, 'event': 'test1'}, {'trial': 1, 'lag': 24, 'event': 'test2'}, {'trial': 1, 'lag': 11, 'event': 'test1'}, {'trial': 1, 'lag': 11, 'event': 'test2'}, {'trial': 0, 'lag': 12, 'event': 'test1'}, {'trial': 0, 'lag': 12, 'event': 'test2'}, {'trial': 1, 'lag': 25, 'event': 'test1'}, {'trial': 1, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 10, 'event': 'study'}, {'trial': 0, 'lag': 2, 'event': 'study'}, {'trial': 0, 'lag': 24, 'event': 'test1'}, {'trial': 0, 'lag': 24, 'event': 'test2'}, {'trial': 0, 'lag': 2, 'event': 'test1'}, {'trial': 0, 'lag': 2, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'study'}, {'trial': 0, 'lag': 25, 'event': 'test1'}, {'trial': 0, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'test1'}, {'trial': 1, 'lag': 2, 'event': 'test2'}, {'trial': 1, 'lag': 10, 'event': 'test1'}, {'trial': 1, 'lag': 10, 'event': 'test2'}],
#
[{'trial': 0, 'lag': 10, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'study'}, {'trial': 1, 'lag': 0, 'event': 'test1'}, {'trial': 1, 'lag': 0, 'event': 'test2'}, {'trial': 0, 'lag': 11, 'event': 'study'}, {'trial': 0, 'lag': 12, 'event': 'study'}, {'trial': 0, 'lag': 1, 'event': 'study'}, {'trial': 1, 'lag': 23, 'event': 'study'}, {'trial': 0, 'lag': 1, 'event': 'test1'}, {'trial': 0, 'lag': 1, 'event': 'test2'}, {'trial': 0, 'lag': 25, 'event': 'study'}, {'trial': 0, 'lag': 10, 'event': 'test1'}, {'trial': 0, 'lag': 10, 'event': 'test2'}, {'trial': 0, 'lag': 24, 'event': 'study'}, {'trial': 1, 'lag': 10, 'event': 'study'}, {'trial': 1, 'lag': 25, 'event': 'study'}, {'trial': 0, 'lag': 11, 'event': 'test1'}, {'trial': 0, 'lag': 11, 'event': 'test2'}, {'trial': 0, 'lag': 12, 'event': 'test1'}, {'trial': 0, 'lag': 12, 'event': 'test2'}, {'trial': 0, 'lag': 2, 'event': 'study'}, {'trial': 1, 'lag': 12, 'event': 'study'}, {'trial': 1, 'lag': 24, 'event': 'study'}, {'trial': 0, 'lag': 2, 'event': 'test1'}, {'trial': 0, 'lag': 2, 'event': 'test2'}, {'trial': 1, 'lag': 10, 'event': 'test1'}, {'trial': 1, 'lag': 10, 'event': 'test2'}, {'trial': 1, 'lag': 1, 'event': 'study'}, {'trial': 0, 'lag': 23, 'event': 'study'}, {'trial': 1, 'lag': 1, 'event': 'test1'}, {'trial': 1, 'lag': 1, 'event': 'test2'}, {'trial': 1, 'lag': 23, 'event': 'test1'}, {'trial': 1, 'lag': 23, 'event': 'test2'}, {'trial': 1, 'lag': 11, 'event': 'study'}, {'trial': 1, 'lag': 12, 'event': 'test1'}, {'trial': 1, 'lag': 12, 'event': 'test2'}, {'trial': 0, 'lag': 25, 'event': 'test1'}, {'trial': 0, 'lag': 25, 'event': 'test2'}, {'trial': 0, 'lag': 24, 'event': 'test1'}, {'trial': 0, 'lag': 24, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'study'}, {'trial': 1, 'lag': 25, 'event': 'test1'}, {'trial': 1, 'lag': 25, 'event': 'test2'}, {'trial': 1, 'lag': 2, 'event': 'test1'}, {'trial': 1, 'lag': 2, 'event': 'test2'}, {'trial': 1, 'lag': 11, 'event': 'test1'}, {'trial': 1, 'lag': 11, 'event': 'test2'}, {'trial': 1, 'lag': 24, 'event': 'test1'}, {'trial': 1, 'lag': 24, 'event': 'test2'}, {'trial': 0, 'lag': 0, 'event': 'study'}, {'trial': 0, 'lag': 0, 'event': 'test1'}, {'trial': 0, 'lag': 0, 'event': 'test2'}, {'trial': 0, 'lag': 23, 'event': 'test1'}, {'trial': 0, 'lag': 23, 'event': 'test2'}]]


prac_list = [{'trial': 0, 'lag': 1, 'event': 'study'},
{'trial': 0, 'lag': 23, 'event': 'study'},
{'trial': 0, 'lag': 1, 'event': 'test1'},
{'trial': 0, 'lag': 1, 'event': 'test2'},
{'trial': 0, 'lag': 0, 'event': 'study'},
{'trial': 0, 'lag': 0, 'event': 'test1'},
{'trial': 0, 'lag': 0, 'event': 'test2'},
{'trial': 0, 'lag': 10, 'event': 'study'},
{'trial': 1, 'lag': 1, 'event': 'study'},
{'trial': 0, 'lag': 2, 'event': 'study'},
{'trial': 1, 'lag': 1, 'event': 'test1'},
{'trial': 1, 'lag': 1, 'event': 'test2'},
{'trial': 0, 'lag': 2, 'event': 'test1'},
{'trial': 0, 'lag': 2, 'event': 'test2'},
{'trial': 2, 'lag': 1, 'event': 'study'},
{'trial': 0, 'lag': 7, 'event': 'study'},
{'trial': 2, 'lag': 1, 'event': 'test1'},
{'trial': 2, 'lag': 1, 'event': 'test2'},
{'trial': 0, 'lag': 10, 'event': 'test1'},
{'trial': 0, 'lag': 10, 'event': 'test2'},
{'trial': 1, 'lag': 0, 'event': 'study'},
{'trial': 1, 'lag': 0, 'event': 'test1'},
{'trial': 1, 'lag': 0, 'event': 'test2'},
{'trial': 0, 'lag': 7, 'event': 'test1'},
{'trial': 0, 'lag': 7, 'event': 'test2'},
{'trial': 0, 'lag': 23, 'event': 'test1'},
{'trial': 0, 'lag': 23, 'event': 'test2'}]
